project:
  type: website
  
execute:
  freeze: auto

website:
  title: "elliotsheehan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - elliotsheehan2.qmd

format:
  html:
    theme:
      - cerulean
      - brand
    css: styles.css
    toc: true

editor: visual

